#!/usr/bin/env bash
#Word Count

echo "Please enter a phrase"
read input_phrase

word_count=$(echo "$input_phrase" | wc -w)
space_count=$(echo "$input_phrase" | tr -cd ' ' |wc -c)

echo "Number of words: $word_count"
echo "Number of white spaces: $space_count"
